WINDOW_SIZE_MINUTE = 150
STEP_SIZE_MINUTE = 15
WINDOW_SIZE_INT = 10
STEP_SIZE_INT = 1

NUM_INVERTER = 22
NUM_OUTPUT = 4
NUM_FEATURES = 5
LEARNING_RATE = 1
VAL_SPLIT = 0.3
HIDDEN_DIM = 50
EPOCHS = 100
BATCH_SIZE = 64

SCALER_PATH = 'Data/Extract/scaler_plant_{}.pkl'
MODEL_PATH = 'LSTM/best_model.pt'
